### ISSUE TITLE
Levantamento bibliográfico sobre funções de leitura de palavras-chave e termos em arquivos texto

### ISSUE THREAD

**Issue by evaldo** [evaldo/dbverification#1]
To understand search for words or letters in a text file using Java programming language

**Comment by evaldo** [comment]
This issue is regarding techniques for accessing to files text using Java Language Programming. Pay attention on the milestones defined, I need only an example about this technique.

**Comment by xxweell** [comment]
Como ler arquivos de texto

Programas Java implementam o processamento de arquivos utilizando as classes do pacote java.io. A hierarquia de classes oferecida por este pacote, apresentada de forma parcial na Figura 1, é relativamente grande e complexa, oferecendo mais de 50 classes distintas para o processamento de entrada e saída em arquivos baseados em bytes e caracteres e arquivos de acesso aleatório. Os arquivos são abertos criando-se objetos através de uma das classes de fluxo, citando:

FileInputStream: para entrada baseada em bytes de um arquivo.
FileOutputStream: para saída baseada em bytes para um arquivo.
RandomAccessFile: para entrada e saída baseada em bytes de e para um arquivo.
FileReader: para entrada baseada em caracteres de um arquivo.
FileWriter: para saída baseada em caracteres para um arquivo.

Desenvolvendo a Aplicação Java
Nos arquivos de texto, os dados são organizados como uma sequência de caracteres dividida em linhas terminadas por um caractere de fim de linha (\n). A interação de um programa com um dispositivo através de arquivos passa por três etapas: abertura do arquivo, leitura dos dados e fechamento do arquivo.

A Listagem 1 apresenta como utilizar as classes FileReader e BufferedReader na abertura e leitura de dados baseada em caracteres de um arquivo de texto. O método read() é empregado na leitura de um caractere enquanto que o método readLine() deverá ser aplicado na leitura de uma linha do arquivo texto.

Listagem 1. Lendo dados de um arquivo texto.
Listagem 1. Lendo dados de um arquivo texto.

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
 
public class Exemplo {
 
  public static void main(String[] args) {
    Scanner ler = new Scanner(System.in);
 
    System.out.printf("Informe o nome de arquivo texto:\n");
    String nome = ler.nextLine();
 
    System.out.printf("\nConteúdo do arquivo texto:\n");
    try {
      FileReader arq = new FileReader(nome);
      BufferedReader lerArq = new BufferedReader(arq);
      String linha = lerArq.readLine(); // lê a primeira linha
// a variável "linha" recebe o valor "null" quando o processo
// de repetição atingir o final do arquivo texto
      while (linha != null) {
        System.out.printf("%s\n", linha);
 
        linha = lerArq.readLine(); // lê da segunda até a última linha
      }
 
      arq.close();
    } catch (IOException e) {
        System.err.printf("Erro na abertura do arquivo: %s.\n",
          e.getMessage());
    }
 
    System.out.println();
  }
}
Entendendo o código fonte da Listagem 1:

O usuário final informa o nome do arquivo que será aberto para operações de entrada através do objeto arq, instanciado e criado a partir da classe FileReader;

Objeto de leitura lerArq é associado a um fluxo de entrada de dados baseado em caracteres através da classe BufferedReader;

Definido o arquivo de texto externo, foi implementado um processo de repetição (while) para ler todas as linhas do arquivo a fim de exibi-las no fluxo padrão de saída System.out;

O tratamento de exceções foi implementado usando um bloco try catch com a classe IOException, responsável pelas exceções em operações de entrada e saída. Outras importantes classes de exceções derivadas da classe IOException são: FileNotFoundException, que ocorre se o arquivo não for localizado ou um novo arquivo não puder ser criado; e EOFException, que acontece se houver uma tentativa de ler depois do final do arquivo.

LUCENE

O IndexWriter é o responsável pela criação do índice, ao qual, através desta classe, pode-se adicionar Documents. Enquanto isso, o IndexSearcher tem o papel de executar a busca no índice. Os critérios de busca são passados para a função de busca do Searcher através do Objeto Query. Em seguida, o Objeto Query é construído através da TermQuery, para o qual passamos como parâmetro o nome do campo a ser procurado e o valor que possivelmente ele contém.

Veja exemplo de Indexação conforme código abaixo:

package info.glaucioguerra.main;

import java.io.FileInputStream;

import java.io.FileReader;

import java.io.IOException;

import org.apache.lucene.analysis.Analyzer;

import org.apache.lucene.analysis.standard.StandardAnalyzer;

import org.apache.lucene.document.Document;

import org.apache.lucene.document.Field;

import org.apache.lucene.index.IndexWriter;

import org.apache.lucene.store.Directory;

import org.apache.lucene.store.FSDirectory;


public class Main {

         public static void main(String[] args) {

                   Document document = new Document();

                   try {

                            FileInputStream arquivo = new FileInputStream("c:/arquivo.txt");

                            Directory directory = FSDirectory.getDirectory("c:/indice", true);

                            Analyzer analyzer = new StandardAnalyzer();

                            IndexWriter writer = new IndexWriter(directory, analyzer, true);

                            document.add(new Field("arquivo", "c:/arquivo.txt",Field.Store.YES, Field.Index.NO));

                            document.add(new Field("conteudo", new FileReader(arquivo.getFD())));

                            writer.addDocument(document);

                            writer.close();

arquivo.close();

                   } catch (IOException e) {

                            e.printStackTrace();
                   }
         }
}

 

Na primeira linha do código declara-se o Document que será armazenado no nosso índice. Carregamos o arquivo arquivo.txt pelo FileInputStream com o seguinte conteúdo:
“JDK 6 with Java EE

Java EE provides web services, component-model, management, and communications APIs that make it the industry standard for implementing enterprise-class service-oriented architecture (SOA) and Web 2.0 applications.

Build native code with easy Java Native Interface (JNI) connections, or accelerate your Java development by leveraging DTrace, Containers, and ZFS. Get Sun's latest development platform with Sun Studio compilers and tools for C/C++/Fortran, NetBeans IDE, and the next-generation Solaris operating system all in the Solaris Express, Developer Edition.”

A escolha deste texto para indexação foi feita porque estamos utilizando o Analyser padrão do Lucene, que reconhece as stop word’s no idioma Inglês.

A classe Directory informa o diretório onde serão armazenados os arquivos do Lucene.  O parâmetro “true” informa que um novo índice será criado, ou destruído caso já exista algum. Logo em seguida temos a classe Analyser, responsável pela extração do texto, como já mencionamos. A IndexWriter recebe como parâmetro o Directory e o Analyser para efetuar a gravação do índice.

A parte do código que merece mais atenção é a criação do Document e a organização de seus Fields. No nosso exemplo estamos criando dois Fields, um para armazenar o nome do arquivo e o outro para guardar o conteúdo.

Analisando o trecho de código:
document.add(new Field("arquivo", "c:/arquivo.txt",Field.Store.YES, Field.Index.NO));

No caso supracidado, adiciona-se um Field para o Document com o nome arquivo e o seu conteúdo é o nome do arquivo do FileInputStream. O parâmetro Field.Store.YES define que o Field deve ser armazenado no Índice. Já o segundo parâmetro define que o Field não deve ser indexado. Em outras palavras, o Field arquivo é armazenado no índice, mas não é um campo indexado, servindo somente para informar o nome do arquivo que foi indexado.

Analisando a criação do segundo Field no Document:
document.add(new Field("conteudo", new FileReader(arquivo.getFD())));

O primeiro parâmetro indica o nome do Field e o segundo um FileReader que fornece a leitura de uma cadeia de caracteres. Este Field será armazenado e indexado.

**Comment by evaldo** [comment]
Como ler (ou varrer/manter) letras ou strings em Java:
http://www.devmedia.com.br/trabalhando-com-string-string-em-java-parte-1/21737
http://www.javaprogressivo.net/2014/01/Como-ler-caracteres-Strings-Bytes-de-arquivos.html
http://blog.caelum.com.br/lendo-arquivos-texto-em-java/

Caractere a Caractere (links e exemplos):
Scanner s = new Scanner(System.in);
String nome = s.nextLine();
for(int i = 0; i < nome.length(); i++) {
  System.out.println(nome.charAt(i));
}

Link muito bom sobre strings:
http://javanoroeste.com.br/javanoroeste/novo/artigos/caracter_string.html#Extraindo

**Comment by xxweell** [comment]
Estudando...

**Comment by evaldo** [comment]
ISSUE finalizada.
